const String GITHUB_RESULT = """
{
  "total_count": 18783,
  "incomplete_results": false,
  "items": [
    {
      "login": "Marcos",
      "id": 181829,
      "node_id": "MDQ6VXNlcjE4MTgyOQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/181829?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Marcos",
      "html_url": "https://github.com/Marcos",
      "followers_url": "https://api.github.com/users/Marcos/followers",
      "following_url": "https://api.github.com/users/Marcos/following{/other_user}",
      "gists_url": "https://api.github.com/users/Marcos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Marcos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Marcos/subscriptions",
      "organizations_url": "https://api.github.com/users/Marcos/orgs",
      "repos_url": "https://api.github.com/users/Marcos/repos",
      "events_url": "https://api.github.com/users/Marcos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Marcos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosnils",
      "id": 1578458,
      "node_id": "MDQ6VXNlcjE1Nzg0NTg=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1578458?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosnils",
      "html_url": "https://github.com/marcosnils",
      "followers_url": "https://api.github.com/users/marcosnils/followers",
      "following_url": "https://api.github.com/users/marcosnils/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosnils/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosnils/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosnils/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosnils/orgs",
      "repos_url": "https://api.github.com/users/marcosnils/repos",
      "events_url": "https://api.github.com/users/marcosnils/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosnils/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcoscaceres",
      "id": 870154,
      "node_id": "MDQ6VXNlcjg3MDE1NA==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/870154?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcoscaceres",
      "html_url": "https://github.com/marcoscaceres",
      "followers_url": "https://api.github.com/users/marcoscaceres/followers",
      "following_url": "https://api.github.com/users/marcoscaceres/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcoscaceres/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcoscaceres/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcoscaceres/subscriptions",
      "organizations_url": "https://api.github.com/users/marcoscaceres/orgs",
      "repos_url": "https://api.github.com/users/marcoscaceres/repos",
      "events_url": "https://api.github.com/users/marcoscaceres/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcoscaceres/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosmoura",
      "id": 1357885,
      "node_id": "MDQ6VXNlcjEzNTc4ODU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1357885?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosmoura",
      "html_url": "https://github.com/marcosmoura",
      "followers_url": "https://api.github.com/users/marcosmoura/followers",
      "following_url": "https://api.github.com/users/marcosmoura/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosmoura/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosmoura/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosmoura/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosmoura/orgs",
      "repos_url": "https://api.github.com/users/marcosmoura/repos",
      "events_url": "https://api.github.com/users/marcosmoura/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosmoura/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosgriselli",
      "id": 14804033,
      "node_id": "MDQ6VXNlcjE0ODA0MDMz",
      "avatar_url": "https://avatars1.githubusercontent.com/u/14804033?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosgriselli",
      "html_url": "https://github.com/marcosgriselli",
      "followers_url": "https://api.github.com/users/marcosgriselli/followers",
      "following_url": "https://api.github.com/users/marcosgriselli/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosgriselli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosgriselli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosgriselli/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosgriselli/orgs",
      "repos_url": "https://api.github.com/users/marcosgriselli/repos",
      "events_url": "https://api.github.com/users/marcosgriselli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosgriselli/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcospereira",
      "id": 4576,
      "node_id": "MDQ6VXNlcjQ1NzY=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/4576?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcospereira",
      "html_url": "https://github.com/marcospereira",
      "followers_url": "https://api.github.com/users/marcospereira/followers",
      "following_url": "https://api.github.com/users/marcospereira/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcospereira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcospereira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcospereira/subscriptions",
      "organizations_url": "https://api.github.com/users/marcospereira/orgs",
      "repos_url": "https://api.github.com/users/marcospereira/repos",
      "events_url": "https://api.github.com/users/marcospereira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcospereira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosbarbero",
      "id": 9323996,
      "node_id": "MDQ6VXNlcjkzMjM5OTY=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/9323996?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosbarbero",
      "html_url": "https://github.com/marcosbarbero",
      "followers_url": "https://api.github.com/users/marcosbarbero/followers",
      "following_url": "https://api.github.com/users/marcosbarbero/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosbarbero/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosbarbero/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosbarbero/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosbarbero/orgs",
      "repos_url": "https://api.github.com/users/marcosbarbero/repos",
      "events_url": "https://api.github.com/users/marcosbarbero/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosbarbero/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcoshenrique-dev",
      "id": 51785898,
      "node_id": "MDQ6VXNlcjUxNzg1ODk4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/51785898?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcoshenrique-dev",
      "html_url": "https://github.com/marcoshenrique-dev",
      "followers_url": "https://api.github.com/users/marcoshenrique-dev/followers",
      "following_url": "https://api.github.com/users/marcoshenrique-dev/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcoshenrique-dev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcoshenrique-dev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcoshenrique-dev/subscriptions",
      "organizations_url": "https://api.github.com/users/marcoshenrique-dev/orgs",
      "repos_url": "https://api.github.com/users/marcoshenrique-dev/repos",
      "events_url": "https://api.github.com/users/marcoshenrique-dev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcoshenrique-dev/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcoschwartz",
      "id": 1475795,
      "node_id": "MDQ6VXNlcjE0NzU3OTU=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1475795?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcoschwartz",
      "html_url": "https://github.com/marcoschwartz",
      "followers_url": "https://api.github.com/users/marcoschwartz/followers",
      "following_url": "https://api.github.com/users/marcoschwartz/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcoschwartz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcoschwartz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcoschwartz/subscriptions",
      "organizations_url": "https://api.github.com/users/marcoschwartz/orgs",
      "repos_url": "https://api.github.com/users/marcoschwartz/repos",
      "events_url": "https://api.github.com/users/marcoschwartz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcoschwartz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcoscastro",
      "id": 5660144,
      "node_id": "MDQ6VXNlcjU2NjAxNDQ=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5660144?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcoscastro",
      "html_url": "https://github.com/marcoscastro",
      "followers_url": "https://api.github.com/users/marcoscastro/followers",
      "following_url": "https://api.github.com/users/marcoscastro/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcoscastro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcoscastro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcoscastro/subscriptions",
      "organizations_url": "https://api.github.com/users/marcoscastro/orgs",
      "repos_url": "https://api.github.com/users/marcoscastro/repos",
      "events_url": "https://api.github.com/users/marcoscastro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcoscastro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thebergamo",
      "id": 1778730,
      "node_id": "MDQ6VXNlcjE3Nzg3MzA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1778730?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thebergamo",
      "html_url": "https://github.com/thebergamo",
      "followers_url": "https://api.github.com/users/thebergamo/followers",
      "following_url": "https://api.github.com/users/thebergamo/following{/other_user}",
      "gists_url": "https://api.github.com/users/thebergamo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thebergamo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thebergamo/subscriptions",
      "organizations_url": "https://api.github.com/users/thebergamo/orgs",
      "repos_url": "https://api.github.com/users/thebergamo/repos",
      "events_url": "https://api.github.com/users/thebergamo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thebergamo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosrivasr",
      "id": 641704,
      "node_id": "MDQ6VXNlcjY0MTcwNA==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/641704?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosrivasr",
      "html_url": "https://github.com/marcosrivasr",
      "followers_url": "https://api.github.com/users/marcosrivasr/followers",
      "following_url": "https://api.github.com/users/marcosrivasr/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosrivasr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosrivasr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosrivasr/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosrivasr/orgs",
      "repos_url": "https://api.github.com/users/marcosrivasr/repos",
      "events_url": "https://api.github.com/users/marcosrivasr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosrivasr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MarcosX",
      "id": 856376,
      "node_id": "MDQ6VXNlcjg1NjM3Ng==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/856376?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarcosX",
      "html_url": "https://github.com/MarcosX",
      "followers_url": "https://api.github.com/users/MarcosX/followers",
      "following_url": "https://api.github.com/users/MarcosX/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarcosX/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarcosX/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarcosX/subscriptions",
      "organizations_url": "https://api.github.com/users/MarcosX/orgs",
      "repos_url": "https://api.github.com/users/MarcosX/repos",
      "events_url": "https://api.github.com/users/MarcosX/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarcosX/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcostark",
      "id": 3633560,
      "node_id": "MDQ6VXNlcjM2MzM1NjA=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3633560?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcostark",
      "html_url": "https://github.com/marcostark",
      "followers_url": "https://api.github.com/users/marcostark/followers",
      "following_url": "https://api.github.com/users/marcostark/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcostark/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcostark/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcostark/subscriptions",
      "organizations_url": "https://api.github.com/users/marcostark/orgs",
      "repos_url": "https://api.github.com/users/marcostark/repos",
      "events_url": "https://api.github.com/users/marcostark/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcostark/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MarcoSero",
      "id": 867996,
      "node_id": "MDQ6VXNlcjg2Nzk5Ng==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/867996?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarcoSero",
      "html_url": "https://github.com/MarcoSero",
      "followers_url": "https://api.github.com/users/MarcoSero/followers",
      "following_url": "https://api.github.com/users/MarcoSero/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarcoSero/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarcoSero/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarcoSero/subscriptions",
      "organizations_url": "https://api.github.com/users/MarcoSero/orgs",
      "repos_url": "https://api.github.com/users/MarcoSero/repos",
      "events_url": "https://api.github.com/users/MarcoSero/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarcoSero/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosaureliodiasmoura",
      "id": 8454273,
      "node_id": "MDQ6VXNlcjg0NTQyNzM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/8454273?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosaureliodiasmoura",
      "html_url": "https://github.com/marcosaureliodiasmoura",
      "followers_url": "https://api.github.com/users/marcosaureliodiasmoura/followers",
      "following_url": "https://api.github.com/users/marcosaureliodiasmoura/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosaureliodiasmoura/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosaureliodiasmoura/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosaureliodiasmoura/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosaureliodiasmoura/orgs",
      "repos_url": "https://api.github.com/users/marcosaureliodiasmoura/repos",
      "events_url": "https://api.github.com/users/marcosaureliodiasmoura/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosaureliodiasmoura/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "cardinot",
      "id": 4231565,
      "node_id": "MDQ6VXNlcjQyMzE1NjU=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/4231565?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cardinot",
      "html_url": "https://github.com/cardinot",
      "followers_url": "https://api.github.com/users/cardinot/followers",
      "following_url": "https://api.github.com/users/cardinot/following{/other_user}",
      "gists_url": "https://api.github.com/users/cardinot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cardinot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cardinot/subscriptions",
      "organizations_url": "https://api.github.com/users/cardinot/orgs",
      "repos_url": "https://api.github.com/users/cardinot/repos",
      "events_url": "https://api.github.com/users/cardinot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cardinot/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MarcosPalaciosIII",
      "id": 25996499,
      "node_id": "MDQ6VXNlcjI1OTk2NDk5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/25996499?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarcosPalaciosIII",
      "html_url": "https://github.com/MarcosPalaciosIII",
      "followers_url": "https://api.github.com/users/MarcosPalaciosIII/followers",
      "following_url": "https://api.github.com/users/MarcosPalaciosIII/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarcosPalaciosIII/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarcosPalaciosIII/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarcosPalaciosIII/subscriptions",
      "organizations_url": "https://api.github.com/users/MarcosPalaciosIII/orgs",
      "repos_url": "https://api.github.com/users/MarcosPalaciosIII/repos",
      "events_url": "https://api.github.com/users/MarcosPalaciosIII/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarcosPalaciosIII/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosd4h",
      "id": 17311749,
      "node_id": "MDQ6VXNlcjE3MzExNzQ5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/17311749?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosd4h",
      "html_url": "https://github.com/marcosd4h",
      "followers_url": "https://api.github.com/users/marcosd4h/followers",
      "following_url": "https://api.github.com/users/marcosd4h/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosd4h/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosd4h/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosd4h/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosd4h/orgs",
      "repos_url": "https://api.github.com/users/marcosd4h/repos",
      "events_url": "https://api.github.com/users/marcosd4h/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosd4h/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosptf",
      "id": 1637541,
      "node_id": "MDQ6VXNlcjE2Mzc1NDE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1637541?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosptf",
      "html_url": "https://github.com/marcosptf",
      "followers_url": "https://api.github.com/users/marcosptf/followers",
      "following_url": "https://api.github.com/users/marcosptf/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosptf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosptf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosptf/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosptf/orgs",
      "repos_url": "https://api.github.com/users/marcosptf/repos",
      "events_url": "https://api.github.com/users/marcosptf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosptf/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosan93",
      "id": 39841620,
      "node_id": "MDQ6VXNlcjM5ODQxNjIw",
      "avatar_url": "https://avatars2.githubusercontent.com/u/39841620?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosan93",
      "html_url": "https://github.com/marcosan93",
      "followers_url": "https://api.github.com/users/marcosan93/followers",
      "following_url": "https://api.github.com/users/marcosan93/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosan93/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosan93/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosan93/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosan93/orgs",
      "repos_url": "https://api.github.com/users/marcosan93/repos",
      "events_url": "https://api.github.com/users/marcosan93/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosan93/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "nsfmc",
      "id": 216572,
      "node_id": "MDQ6VXNlcjIxNjU3Mg==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/216572?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nsfmc",
      "html_url": "https://github.com/nsfmc",
      "followers_url": "https://api.github.com/users/nsfmc/followers",
      "following_url": "https://api.github.com/users/nsfmc/following{/other_user}",
      "gists_url": "https://api.github.com/users/nsfmc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nsfmc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nsfmc/subscriptions",
      "organizations_url": "https://api.github.com/users/nsfmc/orgs",
      "repos_url": "https://api.github.com/users/nsfmc/repos",
      "events_url": "https://api.github.com/users/nsfmc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nsfmc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosvafg",
      "id": 10941438,
      "node_id": "MDQ6VXNlcjEwOTQxNDM4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/10941438?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosvafg",
      "html_url": "https://github.com/marcosvafg",
      "followers_url": "https://api.github.com/users/marcosvafg/followers",
      "following_url": "https://api.github.com/users/marcosvafg/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosvafg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosvafg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosvafg/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosvafg/orgs",
      "repos_url": "https://api.github.com/users/marcosvafg/repos",
      "events_url": "https://api.github.com/users/marcosvafg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosvafg/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcoscv-work",
      "id": 7963804,
      "node_id": "MDQ6VXNlcjc5NjM4MDQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/7963804?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcoscv-work",
      "html_url": "https://github.com/marcoscv-work",
      "followers_url": "https://api.github.com/users/marcoscv-work/followers",
      "following_url": "https://api.github.com/users/marcoscv-work/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcoscv-work/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcoscv-work/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcoscv-work/subscriptions",
      "organizations_url": "https://api.github.com/users/marcoscv-work/orgs",
      "repos_url": "https://api.github.com/users/marcoscv-work/repos",
      "events_url": "https://api.github.com/users/marcoscv-work/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcoscv-work/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Marcos-Costa",
      "id": 19848508,
      "node_id": "MDQ6VXNlcjE5ODQ4NTA4",
      "avatar_url": "https://avatars1.githubusercontent.com/u/19848508?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Marcos-Costa",
      "html_url": "https://github.com/Marcos-Costa",
      "followers_url": "https://api.github.com/users/Marcos-Costa/followers",
      "following_url": "https://api.github.com/users/Marcos-Costa/following{/other_user}",
      "gists_url": "https://api.github.com/users/Marcos-Costa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Marcos-Costa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Marcos-Costa/subscriptions",
      "organizations_url": "https://api.github.com/users/Marcos-Costa/orgs",
      "repos_url": "https://api.github.com/users/Marcos-Costa/repos",
      "events_url": "https://api.github.com/users/Marcos-Costa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Marcos-Costa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosh",
      "id": 2643972,
      "node_id": "MDQ6VXNlcjI2NDM5NzI=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/2643972?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosh",
      "html_url": "https://github.com/marcosh",
      "followers_url": "https://api.github.com/users/marcosh/followers",
      "following_url": "https://api.github.com/users/marcosh/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosh/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosh/orgs",
      "repos_url": "https://api.github.com/users/marcosh/repos",
      "events_url": "https://api.github.com/users/marcosh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosh/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "sn3fru",
      "id": 9492652,
      "node_id": "MDQ6VXNlcjk0OTI2NTI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/9492652?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sn3fru",
      "html_url": "https://github.com/sn3fru",
      "followers_url": "https://api.github.com/users/sn3fru/followers",
      "following_url": "https://api.github.com/users/sn3fru/following{/other_user}",
      "gists_url": "https://api.github.com/users/sn3fru/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sn3fru/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sn3fru/subscriptions",
      "organizations_url": "https://api.github.com/users/sn3fru/orgs",
      "repos_url": "https://api.github.com/users/sn3fru/repos",
      "events_url": "https://api.github.com/users/sn3fru/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sn3fru/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosdeseul",
      "id": 8097987,
      "node_id": "MDQ6VXNlcjgwOTc5ODc=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8097987?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosdeseul",
      "html_url": "https://github.com/marcosdeseul",
      "followers_url": "https://api.github.com/users/marcosdeseul/followers",
      "following_url": "https://api.github.com/users/marcosdeseul/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosdeseul/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosdeseul/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosdeseul/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosdeseul/orgs",
      "repos_url": "https://api.github.com/users/marcosdeseul/repos",
      "events_url": "https://api.github.com/users/marcosdeseul/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosdeseul/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcoslin",
      "id": 3048916,
      "node_id": "MDQ6VXNlcjMwNDg5MTY=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3048916?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcoslin",
      "html_url": "https://github.com/marcoslin",
      "followers_url": "https://api.github.com/users/marcoslin/followers",
      "following_url": "https://api.github.com/users/marcoslin/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcoslin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcoslin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcoslin/subscriptions",
      "organizations_url": "https://api.github.com/users/marcoslin/orgs",
      "repos_url": "https://api.github.com/users/marcoslin/repos",
      "events_url": "https://api.github.com/users/marcoslin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcoslin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "marcosvcorsi",
      "id": 5308575,
      "node_id": "MDQ6VXNlcjUzMDg1NzU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5308575?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marcosvcorsi",
      "html_url": "https://github.com/marcosvcorsi",
      "followers_url": "https://api.github.com/users/marcosvcorsi/followers",
      "following_url": "https://api.github.com/users/marcosvcorsi/following{/other_user}",
      "gists_url": "https://api.github.com/users/marcosvcorsi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marcosvcorsi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marcosvcorsi/subscriptions",
      "organizations_url": "https://api.github.com/users/marcosvcorsi/orgs",
      "repos_url": "https://api.github.com/users/marcosvcorsi/repos",
      "events_url": "https://api.github.com/users/marcosvcorsi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marcosvcorsi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}

""";
